name: Backend - Build & Push Docker

on:
  push:
    branches: [ master ]   # change if your default branch is 'main'
    paths:
      - "backend/**"
      - ".github/workflows/backend-docker-publish.yml"
  workflow_dispatch: {}

env:
  IMAGE_NAME: blazhe/activity-tracker-backend

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        # fetch-depth 0 gives us the commit SHA for tagging
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.sha_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
