name: Backend - Build & Push Docker

on:
  push:
    branches: [ master ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-docker-publish.yml"
  workflow_dispatch: {}

env:
  IMAGE_NAME: blazhe/activity-tracker-backend

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ✅ Prepare a safe short tag (never empty)
      - name: Compute image tags
        run: |
          SHA_SHORT="${GITHUB_SHA::7}"
          if [ -z "$SHA_SHORT" ]; then SHA_SHORT="ci"; fi
          echo "SHA_SHORT=$SHA_SHORT" >> $GITHUB_ENV

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.SHA_SHORT }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
